# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jiani Chen
title: Graduate research assistent
email: jiani.chen@uga.edu
website: https://jianic.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: JianiCh
github_username:  JianiC
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: Jiani Chen
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
 # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am current a PhD bioinformatic student at the university of Georgia, I am studying the infectious dynamic caused by respiratory virus using <mark>phylodynamics</mark> approach.
  I am most skilled in: <mark>Bayesian phylogenetic analysis </mark> and <mark>virus genome assembly</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: A novel and extenable nomenclature system of RSV
        link: nextstrain.org/community/JianiC/rsv-genotype/
        # link_text: Project Website
        additional_links:
          - title: JianiC/rsv-genotype
            icon: fab fa-github
            url: github.com/JianiC/rsv-genotype
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
              I aim to propose a novel RSV nomenclature system which provides a convenient and sustainable way to refer to the emergence of RSV strains.We also provided an RSV classification tool to perform RSV genotype assignment.
     - layout: top-middle
        title: customized IRMA module for RSV genome assembly
        link: github.com/JianiC/IRMA-RSV
        # link_text: Project Website
        additional_links:
          - title:  JianiC/IRMA-RSV
            icon: fab fa-github
            url: github.com/JianiC/IRMA-RSV
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
             A coustomized genome assembly read modules allowing the reads with different coverage across regions
     - layout: top-middle
        title: RSV T-cell epiope analysis 
        link: github.com/JianiC/RSV_Epitope
        # link_text: Project Website
        additional_links:
          - title:  JianiC/JianiC/RSV_Epitope
            icon: fab fa-github
            url: github.com/JianiC/RSV_Epitope
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
             I am working on computational RSV vaccine development via predicting T cell epitopes.            

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tangshan Kailuan Hospital
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Internship
        caption: 2015.6-2016.3
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            I worked in a hostiptal for 1 years when I was in the medical school in China

      - layout: left
        title: China College Students Innovation & Entrepreneurship Plan  
        #link: boringcompany.com
        # link_text: boringcompany.com
        #sub_title: Internship
        caption: 2014-2015
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            This is the first time when I think about science
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Georgia
        caption: 2018-present
        sub_title: PhD Bioinformatic
        quote: >
        description: | # this will include new lines to allow paragraphs
            I am studing infectious dynamic in Dr. Justin Bahl lab, we are using immunoinformatic, phylodynamic, mathamatic modeling as well as other bioinformatics approaches.
            
 - layout: left
        title: University of Kansas
        caption: 2016-2018
        sub_title: Master in Pharmacology and Toxicologyc
        quote: >
        description: | # this will include new lines to allow paragraphs

 - layout: left
        title: Guilin Medical University
        caption: 2011-2016
        sub_title: MBS in Clinical Laboratory Scinece
        quote: >
        description: | # this will include new lines to allow paragraphs

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
##      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
 #     - Gaming
 #     - Knitting
 #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
