title: Jiani Chen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jiani-chen-9a8031149">LinkedIn</a> 
  </p>
  
  <p align="justify">
  I am pursing ph.D degree in Bioinformatics at University of Georgia.
  Before starting my phd, I earned master's degree at Pharmacology and Toxicology at the University of Kansas and Medical degree ( Bachelor's) at Guilin Medical University in China.
  <br><br>
  I currently focus on infectious disease caused by RNA virus using phylodynamics and statistics modeling approach.
  I have experience with NGS and other type of medical claims data. Not only a programmer or modeler but a person try to solve all problems in my life.
  <br><br>
  
  </p>
